language: python
python:
 # - "3.6"      # current default Python on Travis CI
 # - "3.7"
  - "3.8"
install:
  - pip3 install -r requirements.txt

# command to run tests
script:
  - pytest test_events_by_date
  - pytest test_helsinki_api_integration
  - coverage run -m --source=. test_events_by_date
  - coverage report